# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-09 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normalization', '0004_auto_20170709_0750'),
        ('morphology', '0002_auto_20160617_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialect',
            name='model_to_normalize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='normalization.Model'),
        ),
    ]
