# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-09 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0003_dialect_model_to_normalize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialect',
            name='model_to_normalize',
        ),
    ]
