# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-20 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0005_auto_20180304_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normalizationmodel',
            name='to_dialect',
        ),
        migrations.AddField(
            model_name='normalizationmodel',
            name='to_dialect',
            field=models.ManyToManyField(to='morphology.Dialect'),
        ),
    ]
