# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-07 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('morphology', '0002_auto_20160617_1150'),
        ('corpora', '0007_auto_20170707_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordings', models.ManyToManyField(blank=True, to='corpora.Recording')),
                ('to_dialect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.Dialect')),
            ],
        ),
    ]
