# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-07 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='name',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
