# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-07 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normalization', '0002_model_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='recordings',
        ),
    ]
