# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-09 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalization', '0003_remove_model_recordings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='to_dialect',
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
