# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-09 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0004_remove_dialect_model_to_normalize'),
        ('corpora', '0009_remove_recording_model_to_normalize'),
        ('normalization', '0004_auto_20170709_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='recordings_to_retrain',
            field=models.ManyToManyField(blank=True, to='corpora.Recording'),
        ),
        migrations.AddField(
            model_name='model',
            name='to_dialect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='morphology.Dialect', verbose_name='Dialect'),
        ),
    ]
