# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-04 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0005_auto_20180304_2107'),
        ('normalization', '0006_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='to_dialect',
        ),
        migrations.AddField(
            model_name='model',
            name='to_dialect',
            field=models.ManyToManyField(blank=True, to='morphology.Dialect', verbose_name='Dialect'),
        ),
    ]
