# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-09 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0008_recording_model_to_normalize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='model_to_normalize',
        ),
    ]
