# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-10 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0009_remove_recording_model_to_normalize'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Manually checked'),
        ),
    ]
