# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-16 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0010_recording_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='auto_annotated',
            field=models.BooleanField(default=False, verbose_name='Automatically annotated'),
        ),
    ]
